BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SELECT no_plan();
SET session_replication_role=replica;
INSERT INTO public.users(user_id,anonymous_pseudonym,avatar_seed,recovery_key_hash,display_name,display_name_normalized,username_normalized,user_role,account_status,birth_year)
SELECT ('1a720000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,'jobnotice'||n,'jobnotice'||n,'x','Notice Test','notice test','jobnotice'||n,r::public.user_role_type,'active',1990
FROM (VALUES(1,'super_admin'),(2,'admin'),(3,'moderator'),(4,'support'),(5,'analyst'),(6,'read_only_auditor'),(7,'normal')) roles(n,r);
INSERT INTO auth.users(id,aud,role,created_at,updated_at) SELECT user_id,'authenticated','authenticated',now(),now() FROM public.users WHERE anonymous_pseudonym LIKE 'jobnotice%';
SET session_replication_role=origin;
SELECT ok(NOT has_table_privilege('authenticated','private.staff_job_attention','SELECT'),'raw job summary inaccessible');
SELECT ok(NOT has_table_privilege('authenticated','private.staff_inbox_hourly','SELECT'),'raw history inaccessible');
SELECT ok(NOT has_function_privilege('authenticated','private.refresh_staff_job_attention()','EXECUTE'),'clients cannot run the monitor');
SELECT ok(NOT has_function_privilege('anon','public.admin_staff_notification_observability()','EXECUTE'),'anonymous callers cannot read history');
SELECT ok(NOT has_function_privilege('authenticated','public.staff_notification_monitor()','EXECUTE') AND has_function_privilege('service_role','public.staff_notification_monitor()','EXECUTE'),'independent machine monitor is service-only');
SELECT is((public.staff_notification_monitor()->>'enabled')::BOOLEAN,false,'disabled monitoring state is explicit, never healthy');
UPDATE private.staff_inbox_control SET enabled=true,audience_roles=ARRAY['super_admin','admin','moderator','support','analyst','read_only_auditor'];
INSERT INTO public.push_delivery_outbox(event_key,user_id,event_kind,status)
SELECT 'jobnotice-'||i,'1a720000-0000-4000-8000-000000000007','notification','dead' FROM generate_series(1,1002)i;
INSERT INTO public.email_outbox(outbox_id,user_id,template,status) VALUES('1a720000-1000-4000-8000-000000000001','1a720000-0000-4000-8000-000000000007','welcome','failed');
INSERT INTO public.media_scan_jobs(kind,content_id,user_id,lease_id,lease_expires_at)
VALUES('post','1a720000-1000-4000-8000-000000000002','1a720000-0000-4000-8000-000000000007',gen_random_uuid(),now()-interval '16 minutes');
SELECT is(private.refresh_staff_job_attention(),0,'monitor defaults off');
SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claims','{"sub":"1a720000-0000-4000-8000-000000000001","role":"authenticated","aal":"aal1"}',true);
SELECT throws_like($$SELECT public.admin_configure_staff_inbox_sources('1a720000-2000-4000-8000-000000000001',true,true)$$,'%aal2_required%','source configuration requires step-up');
SELECT set_config('request.jwt.claims','{"sub":"1a720000-0000-4000-8000-000000000001","role":"authenticated","aal":"aal2"}',true);
SELECT lives_ok($$SELECT public.admin_configure_staff_inbox_sources('1a720000-2000-4000-8000-000000000001',true,true)$$,'explicit source configuration succeeds');
SELECT lives_ok($$SELECT public.admin_configure_staff_inbox_sources('1a720000-2000-4000-8000-000000000001',true,true)$$,'identical source retry replays');
SELECT throws_like($$SELECT public.admin_configure_staff_inbox_sources('1a720000-2000-4000-8000-000000000001',false,true)$$,'%idempotency_payload_mismatch%','same key cannot change source switches');
RESET ROLE;
SELECT is(private.refresh_staff_job_attention(),3,'three queue notices replace thousands of per-job notices');
SELECT is(private.refresh_staff_job_attention(),0,'same-hour reconciliation is deduplicated');
SELECT ok((SELECT observed_count=1000 AND has_more FROM private.staff_job_attention WHERE queue='push'),'queue sampling has an honest 1000+ bound');
SELECT ok(NOT EXISTS(SELECT 1 FROM private.staff_job_attention s WHERE to_jsonb(s)::text LIKE '%jobnotice%'),'job snapshots contain no recipient fields');
INSERT INTO private.impact_report_snapshots(report_id,report_kind,title,audience,window_start,window_end,generated_by)
VALUES('1a720000-3000-4000-8000-000000000001','monthly_impact','private report title','internal','2026-01-01','2026-01-31','1a720000-0000-4000-8000-000000000001');
SELECT is((SELECT count(*)::int FROM private.staff_event_outbox WHERE source_id='1a720000-3000-4000-8000-000000000001'),0,'report without completed checksum generates no notice');
UPDATE private.impact_report_snapshots SET checksum=repeat('a',64) WHERE report_id='1a720000-3000-4000-8000-000000000001';
UPDATE private.impact_report_snapshots SET checksum=checksum WHERE report_id='1a720000-3000-4000-8000-000000000001';
SELECT is((SELECT count(*)::int FROM private.staff_event_outbox WHERE source_id='1a720000-3000-4000-8000-000000000001'),1,'complete report produces one durable event');
SELECT ok(NOT EXISTS(SELECT 1 FROM private.staff_event_outbox WHERE source_id='1a720000-3000-4000-8000-000000000001' AND to_jsonb(staff_event_outbox)::text LIKE '%private report title%'),'report title is not notification metadata');
SELECT private.process_staff_inbox(100);
SELECT private.process_staff_inbox(100);
SELECT is((SELECT count(*)::int FROM private.staff_inbox_deliveries d JOIN private.staff_event_outbox o USING(event_id) WHERE o.kind LIKE 'job_%' AND d.recipient_id IN(SELECT user_id FROM public.users WHERE anonymous_pseudonym LIKE 'jobnotice%')),6,'job notices only reach the two eligible fixture staff');
SELECT is((SELECT count(*)::int FROM private.staff_inbox_deliveries d JOIN private.staff_event_outbox o USING(event_id) WHERE o.source_id='1a720000-3000-4000-8000-000000000001'),1,'report notice reaches only its requester');
SET LOCAL ROLE authenticated;
SELECT is((SELECT count(*)::int FROM public.admin_staff_inbox_page('all','jobs')),3,'jobs category is filtered before pagination');
SELECT is((SELECT (q->>'count')::INTEGER FROM jsonb_array_elements(public.admin_staff_attention()->'queues')q WHERE q->>'key'='jobs'),100,'Jobs badge saturates at the 99+ threshold');
SELECT is((SELECT destination FROM public.admin_staff_inbox_page('all','reports')),'/impact/reports/1a720000-3000-4000-8000-000000000001','report destination resolves exact snapshot');
SELECT ok((public.admin_staff_notification_observability()->'hours') IS NOT NULL,'authorized historical telemetry RPC works');
SELECT set_config('request.jwt.claims','{"sub":"1a720000-0000-4000-8000-000000000002","role":"authenticated","aal":"aal2"}',true);
SELECT is((SELECT count(*)::int FROM public.admin_staff_inbox_page('all','reports')),0,'other admin cannot see requester notice');
SELECT throws_like('SELECT public.admin_staff_notification_observability()','%not_authorized%','history is super-admin only');
SELECT throws_like($$SELECT public.admin_configure_staff_inbox_sources(gen_random_uuid(),false,false)$$,'%not_authorized%','admin cannot change rollout');
RESET ROLE;
SELECT ok((SELECT batches>=2 AND delivered_events>=4 FROM private.staff_inbox_hourly ORDER BY hour DESC LIMIT 1),'hourly counters retain earlier successful batches');
SELECT ok((SELECT max_delivery_lag_seconds>=0 FROM private.staff_inbox_hourly ORDER BY hour DESC LIMIT 1),'history retains observed maximum, not fabricated percentile');
UPDATE private.staff_job_attention SET measured_at=now()-interval '3 minutes';
SET LOCAL ROLE authenticated;
SELECT is((SELECT count(*)::int FROM public.admin_staff_inbox_page('all','jobs')),0,'stale job snapshots fail closed');
SELECT is((SELECT (q->>'stale')::BOOLEAN FROM jsonb_array_elements(public.admin_staff_attention()->'queues')q WHERE q->>'key'='jobs'),true,'stale badge never shows a fresh count');
RESET ROLE;
SELECT is((public.staff_notification_monitor()->>'job_monitor_stale')::BOOLEAN,true,'independent monitor catches stale queue reconciliation');
SELECT private.refresh_staff_job_attention();
UPDATE private.staff_inbox_control SET job_events_enabled=false,report_events_enabled=false;
SET LOCAL ROLE authenticated;
SELECT is((SELECT count(*)::int FROM public.admin_staff_inbox_page('all','jobs')),0,'source rollback hides existing notices');
SELECT set_config('request.jwt.claims','{"sub":"1a720000-0000-4000-8000-000000000001","role":"authenticated","aal":"aal2"}',true);
SELECT is((SELECT count(*)::int FROM public.admin_staff_inbox_page('all','reports')),0,'report rollback hides requester notice');
RESET ROLE;
UPDATE private.staff_inbox_control SET job_events_enabled=true,report_events_enabled=true;
UPDATE public.users SET account_status='suspended' WHERE user_id='1a720000-0000-4000-8000-000000000001';
SET LOCAL ROLE authenticated;
SELECT throws_like('SELECT public.admin_staff_notification_observability()','%not_authorized%','suspension takes effect without token refresh');
RESET ROLE;
UPDATE public.users SET account_status='active' WHERE user_id='1a720000-0000-4000-8000-000000000001';
SET LOCAL ROLE authenticated;
SELECT set_config('test.checked_report',public.admin_generate_impact_report_checked('1a720000-2000-4000-8000-000000000002','monthly_impact','Replay test','internal','2026-01-01','2026-01-31')::TEXT,true);
SELECT is(public.admin_generate_impact_report_checked('1a720000-2000-4000-8000-000000000002','monthly_impact','Replay test','internal','2026-01-01','2026-01-31')::TEXT,current_setting('test.checked_report'),'report request retries return the same snapshot');
SELECT throws_like($$SELECT public.admin_generate_impact_report_checked('1a720000-2000-4000-8000-000000000002','monthly_impact','Changed test','internal','2026-01-01','2026-01-31')$$,'%idempotency_payload_mismatch%','changed report request cannot reuse a receipt');
RESET ROLE;
SELECT is((SELECT count(*)::INTEGER FROM private.staff_event_outbox WHERE source_id=current_setting('test.checked_report')::UUID),1,'checked generation has one report-ready notice');
SELECT * FROM finish();
ROLLBACK;
