BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SELECT no_plan();
SET session_replication_role=replica;
INSERT INTO public.users(user_id,anonymous_pseudonym,avatar_seed,recovery_key_hash,display_name,display_name_normalized,username_normalized,user_role,account_status,birth_year)
SELECT ('1a730000-0000-4000-8000-'||lpad(n::TEXT,12,'0'))::UUID,'incidenttest'||n,'incidenttest'||n,'x','Incident Operator','incident operator','incidenttest'||n,r::public.user_role_type,'active',1990
FROM (VALUES(1,'super_admin'),(2,'admin'),(3,'moderator'),(4,'support'),(5,'analyst'),(6,'read_only_auditor'),(7,'normal'))t(n,r);
INSERT INTO auth.users(id,aud,role,created_at,updated_at) SELECT user_id,'authenticated','authenticated',now(),now() FROM public.users WHERE anonymous_pseudonym LIKE 'incidenttest%';
SET session_replication_role=origin;
CREATE FUNCTION pg_temp.claim(n INTEGER,aal TEXT DEFAULT 'aal2') RETURNS VOID LANGUAGE sql AS $$SELECT set_config('request.jwt.claims',jsonb_build_object('sub','1a730000-0000-4000-8000-'||lpad(n::TEXT,12,'0'),'role','authenticated','aal',aal)::TEXT,true)::TEXT;$$;
CREATE FUNCTION pg_temp.payload() RETURNS JSONB LANGUAGE sql AS $$SELECT jsonb_build_object('title','Synthetic incident','severity','sev2','services',ARRAY['push'],'commander','1a730000-0000-4000-8000-000000000001','responders',ARRAY['1a730000-0000-4000-8000-000000000002'],'deadline',now()+interval '1 hour','runbook','delivery','signal','push-dead','note','Synthetic private timeline note');$$;
CREATE FUNCTION pg_temp.command(command TEXT,payload JSONB) RETURNS UUID LANGUAGE sql AS $$SELECT public.admin_incident_mutate(gen_random_uuid(),current_setting('test.incident')::UUID,(public.admin_incident_detail(current_setting('test.incident')::UUID)->'incident'->>'version')::BIGINT,command,payload);$$;
SELECT ok(NOT has_table_privilege('authenticated','private.operational_incidents','SELECT'),'raw incidents not exposed');
SELECT ok(NOT has_table_privilege('authenticated','private.incident_events','INSERT'),'timeline not client writable');
SELECT ok(NOT has_function_privilege('anon','public.admin_incident_mutate(uuid,uuid,bigint,text,jsonb)','EXECUTE'),'anonymous mutation denied');
SET LOCAL ROLE authenticated;
SELECT pg_temp.claim(1);
SELECT is(public.admin_incident_queue()->>'enabled','false','defaults disabled');
SELECT throws_like($$SELECT public.admin_incident_mutate(gen_random_uuid(),NULL,NULL,'declare',pg_temp.payload())$$,'%incident_disabled%','disabled API rejects writes');
SELECT pg_temp.claim(1,'aal1');
SELECT throws_like($$SELECT public.admin_configure_incidents(gen_random_uuid(),true)$$,'%aal2_required%','configuration requires MFA');
SELECT pg_temp.claim(1);
SELECT lives_ok($$SELECT public.admin_configure_incidents('1a730000-1000-4000-8000-000000000001',true)$$,'configuration enabled');
SELECT public.admin_configure_incident_audience(gen_random_uuid(),ARRAY['super_admin','admin']);
SELECT lives_ok($$SELECT public.admin_configure_incidents('1a730000-1000-4000-8000-000000000001',true)$$,'configuration retry stable');
SELECT throws_like($$SELECT public.admin_configure_incidents('1a730000-1000-4000-8000-000000000001',false)$$,'%idempotency_payload_mismatch%','changed rollout retry refused');
SELECT pg_temp.claim(2);
SELECT throws_like($$SELECT public.admin_configure_incidents(gen_random_uuid(),false)$$,'%not_authorized%','admin cannot toggle rollout');
SELECT pg_temp.claim(1,'aal1');
SELECT throws_like($$SELECT public.admin_incident_mutate(gen_random_uuid(),NULL,NULL,'declare',pg_temp.payload())$$,'%aal2_required%','direct API mutation requires MFA');
SELECT pg_temp.claim(1);
SELECT throws_like($$SELECT public.admin_incident_mutate(gen_random_uuid(),NULL,NULL,'declare',pg_temp.payload()||'{"user_id":"spoofed"}')$$,'%invalid_command%','unknown actor/payload fields refused');
SELECT throws_like($$SELECT public.admin_incident_mutate(gen_random_uuid(),NULL,NULL,'declare',pg_temp.payload()||'{"commander":"1a730000-0000-4000-8000-000000000007"}')$$,'%invalid_staff%','member cannot be commander');
SELECT throws_like($$SELECT public.admin_incident_mutate(gen_random_uuid(),NULL,NULL,'declare',pg_temp.payload()||'{"responders":["1a730000-0000-4000-8000-000000000003"]}')$$,'%invalid_staff%','assignment does not broaden moderator authority');
SELECT throws_like($$SELECT public.admin_incident_mutate(gen_random_uuid(),NULL,NULL,'declare',pg_temp.payload()||'{"deadline":"infinity"}')$$,'%invalid_deadline%','infinite deadline refused');
SELECT throws_like($$SELECT public.admin_incident_mutate(gen_random_uuid(),NULL,NULL,'declare',pg_temp.payload()||'{"title":"<script>x</script>"}')$$,'%check constraint%','markup title refused');
SELECT set_config('test.incident',public.admin_incident_mutate('1a730000-1000-4000-8000-000000000002',NULL,NULL,'declare',pg_temp.payload())::TEXT,true);
SELECT is(public.admin_incident_mutate('1a730000-1000-4000-8000-000000000002',NULL,NULL,'declare',pg_temp.payload())::TEXT,current_setting('test.incident'),'exact retry returns original incident');
SELECT throws_like($$SELECT public.admin_incident_mutate('1a730000-1000-4000-8000-000000000002',NULL,NULL,'declare',pg_temp.payload()||'{"title":"Different"}')$$,'%idempotency_payload_mismatch%','changed declaration retry refused');
SELECT is(public.admin_incident_detail(current_setting('test.incident')::UUID)->'incident'->>'version','1','duplicate does not advance version');
SELECT is(jsonb_array_length(public.admin_incident_detail(current_setting('test.incident')::UUID)->'events'),1,'one declaration event');
SELECT is(jsonb_array_length(public.admin_incident_queue('active')->'rows'),1,'active queue returns new incident');
SELECT throws_like($$SELECT public.admin_incident_queue('all','all',now(),NULL)$$,'%invalid_queue%','paired cursor enforced');
SELECT throws_like($$SELECT public.admin_incident_queue('all','all',NULL,NULL,1000)$$,'%invalid_queue%','queue cap enforced');
SELECT lives_ok($$SELECT pg_temp.command('note','{"kind":"decision","note":"Synthetic decision"}')$$,'decision appended');
SELECT throws_like($$SELECT public.admin_incident_mutate(gen_random_uuid(),current_setting('test.incident')::UUID,1,'transition','{"status":"investigating","note":"Acknowledge"}')$$,'%workflow_conflict%','stale version rejected');
SELECT throws_like($$SELECT pg_temp.command('transition','{"status":"resolved","note":"Skip phases"}')$$,'%invalid_transition%','lifecycle cannot skip phases');
SELECT lives_ok($$SELECT pg_temp.command('transition','{"status":"investigating","note":"Response started"}')$$,'investigation allowed');
SELECT pg_temp.claim(2);
SELECT is(jsonb_array_length(public.admin_incident_queue('mine')->'rows'),1,'responder has mine queue');
SELECT lives_ok($$SELECT pg_temp.command('coordinate',(pg_temp.payload()-'title')||'{"severity":"sev1"}')$$,'active admin can coordinate');
SELECT is(public.admin_incident_detail(current_setting('test.incident')::UUID)->'incident'->>'severity','sev1','severity persisted');
SELECT lives_ok($$SELECT pg_temp.command('transition','{"status":"mitigating","note":"Mitigation tracked internally"}')$$,'mitigating allowed');
SELECT lives_ok($$SELECT pg_temp.command('transition','{"status":"monitoring","note":"Monitoring outcomes"}')$$,'monitoring allowed');
SELECT lives_ok($$SELECT pg_temp.command('transition','{"status":"resolved","note":"Recovery observed"}')$$,'resolved allowed');
SELECT lives_ok($$SELECT pg_temp.command('action_add',jsonb_build_object('title','Verify restore drill','owner','1a730000-0000-4000-8000-000000000002','deadline',now()+interval '7 days'))$$,'owned postmortem action added');
SELECT throws_like($$SELECT pg_temp.command('transition','{"status":"reviewed","note":"Review complete"}')$$,'%open_postmortem_actions%','unfinished actions block review');
SELECT throws_like($$SELECT pg_temp.command('action_complete','{"action":"1a730000-9999-4000-8000-000000000001"}')$$,'%action_not_open%','foreign or missing action cannot complete');
SELECT lives_ok($$SELECT pg_temp.command('action_complete',jsonb_build_object('action',public.admin_incident_detail(current_setting('test.incident')::UUID)->'actions'->0->>'action_id'))$$,'postmortem action completion recorded');
SELECT lives_ok($$SELECT pg_temp.command('transition','{"status":"reviewed","note":"Review complete"}')$$,'review closes lifecycle');
SELECT throws_like($$SELECT pg_temp.command('note','{"kind":"update","note":"Rewrite reviewed incident"}')$$,'%incident_reviewed%','reviewed records closed to further commands');
SELECT ok(jsonb_array_length(public.admin_incident_detail(current_setting('test.incident')::UUID,3)->'events')=2,'timeline cursor reads older versions only');
SELECT pg_temp.claim(3);
SELECT throws_like('SELECT public.admin_incident_queue()','%not_authorized%','moderator denied');
SELECT pg_temp.claim(4);
SELECT throws_like('SELECT public.admin_incident_queue()','%not_authorized%','support denied');
SELECT pg_temp.claim(5);
SELECT throws_like('SELECT public.admin_incident_queue()','%not_authorized%','analyst denied');
SELECT pg_temp.claim(6);
SELECT throws_like('SELECT public.admin_incident_queue()','%not_authorized%','auditor denied');
SELECT pg_temp.claim(7);
SELECT throws_like('SELECT public.admin_incident_queue()','%not_authorized%','normal member denied');
RESET ROLE;
SELECT throws_like($$UPDATE private.incident_events SET note='rewrite' WHERE incident_id=current_setting('test.incident')::UUID$$,'%immutable_operational_record%','history cannot be rewritten');
SELECT throws_like($$DELETE FROM private.incident_events WHERE incident_id=current_setting('test.incident')::UUID$$,'%immutable_operational_record%','history cannot be deleted');
SELECT ok(NOT EXISTS(SELECT 1 FROM public.audit_log WHERE target_id=current_setting('test.incident')::UUID AND to_jsonb(audit_log)::TEXT LIKE '%Synthetic private timeline note%'),'audit does not duplicate coordination content');
UPDATE public.users SET account_status='suspended' WHERE user_id='1a730000-0000-4000-8000-000000000002';
SET LOCAL ROLE authenticated;
SELECT pg_temp.claim(2);
SELECT throws_like('SELECT public.admin_incident_queue()','%not_authorized%','suspension effective with existing JWT');
SELECT pg_temp.claim(1);
SELECT lives_ok($$SELECT public.admin_configure_incidents(gen_random_uuid(),false)$$,'rollback disables feature');
SELECT is(public.admin_incident_detail(current_setting('test.incident')::UUID)->>'enabled','false','rollback hides existing records');
RESET ROLE;
SELECT is((SELECT count(*)::INTEGER FROM private.operational_incidents WHERE incident_id=current_setting('test.incident')::UUID),1,'rollback preserves record');
SELECT * FROM finish();
ROLLBACK;
