BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SELECT no_plan();
SET session_replication_role=replica;
INSERT INTO public.users(user_id,anonymous_pseudonym,avatar_seed,recovery_key_hash,display_name,display_name_normalized,username_normalized,user_role,account_status,birth_year)
SELECT ('1a740000-0000-4000-8000-'||lpad(n::TEXT,12,'0'))::UUID,'incidentnotice'||n,'incidentnotice'||n,'x','Notice Operator','notice operator','incidentnotice'||n,r::public.user_role_type,'active',1990
FROM (VALUES(1,'super_admin'),(2,'admin'),(3,'moderator'),(4,'support'),(5,'analyst'),(6,'read_only_auditor'),(7,'normal'),(8,'admin'))t(n,r);
INSERT INTO auth.users(id,aud,role,created_at,updated_at) SELECT user_id,'authenticated','authenticated',now(),now() FROM public.users WHERE anonymous_pseudonym LIKE 'incidentnotice%';
SET session_replication_role=origin;
CREATE FUNCTION pg_temp.claim(n INTEGER,aal TEXT DEFAULT 'aal2') RETURNS VOID LANGUAGE sql AS $$SELECT set_config('request.jwt.claims',jsonb_build_object('sub','1a740000-0000-4000-8000-'||lpad(n::TEXT,12,'0'),'role','authenticated','aal',aal)::TEXT,true)::TEXT;$$;
CREATE FUNCTION pg_temp.payload() RETURNS JSONB LANGUAGE sql AS $$SELECT jsonb_build_object('title','Sensitive synthetic title','severity','sev1','services',ARRAY['push'],'commander','1a740000-0000-4000-8000-000000000001','responders',ARRAY['1a740000-0000-4000-8000-000000000002'],'deadline',now()+interval '1 hour','runbook','delivery','signal','push-dead','note','Sensitive synthetic note');$$;
CREATE FUNCTION pg_temp.command(command TEXT,payload JSONB) RETURNS UUID LANGUAGE sql AS $$SELECT public.admin_incident_mutate(gen_random_uuid(),current_setting('test.incident')::UUID,(public.admin_incident_detail(current_setting('test.incident')::UUID)->'incident'->>'version')::BIGINT,command,payload);$$;
SELECT ok(NOT has_function_privilege('authenticated','private.reconcile_incident_deadlines()','EXECUTE'),'clients cannot invoke deadline worker');
SELECT ok(NOT has_function_privilege('anon','public.admin_configure_incident_notices(uuid,boolean)','EXECUTE'),'anonymous configuration denied');
SELECT is(private.reconcile_incident_deadlines(),0,'deadline producer disabled by default');
UPDATE private.staff_inbox_control SET enabled=true,audience_roles=ARRAY['super_admin','admin','moderator','support','analyst','read_only_auditor'];
SET LOCAL ROLE authenticated;
SELECT pg_temp.claim(1);
SELECT public.admin_configure_incidents(gen_random_uuid(),true);
SELECT public.admin_configure_incident_audience(gen_random_uuid(),ARRAY['super_admin','admin']);
SELECT set_config('test.incident',public.admin_incident_mutate(gen_random_uuid(),NULL,NULL,'declare',pg_temp.payload())::TEXT,true);
RESET ROLE;
SELECT is((SELECT count(*)::INTEGER FROM private.staff_event_outbox WHERE source_id=current_setting('test.incident')::UUID),0,'incident notices require a separate source opt-in');
SET LOCAL ROLE authenticated;
SELECT pg_temp.claim(1,'aal1');
SELECT throws_like($$SELECT public.admin_configure_incident_notices(gen_random_uuid(),true)$$,'%aal2_required%','notices configuration requires MFA');
SELECT pg_temp.claim(2);
SELECT throws_like($$SELECT public.admin_configure_incident_notices(gen_random_uuid(),true)$$,'%not_authorized%','ordinary admin cannot change source rollout');
SELECT pg_temp.claim(1);
SELECT lives_ok($$SELECT public.admin_configure_incident_notices('1a740000-1000-4000-8000-000000000001',true)$$,'source rollout enabled');
SELECT lives_ok($$SELECT public.admin_configure_incident_notices('1a740000-1000-4000-8000-000000000001',true)$$,'rollout retry is idempotent');
SELECT throws_like($$SELECT public.admin_configure_incident_notices('1a740000-1000-4000-8000-000000000001',false)$$,'%idempotency_payload_mismatch%','changed retry refused');
SELECT public.admin_incident_mutate('1a740000-1000-4000-8000-000000000002',current_setting('test.incident')::UUID,1,'note','{"kind":"decision","note":"Sensitive synthetic note"}');
SELECT public.admin_incident_mutate('1a740000-1000-4000-8000-000000000002',current_setting('test.incident')::UUID,1,'note','{"kind":"decision","note":"Sensitive synthetic note"}');
RESET ROLE;
SELECT is((SELECT count(*)::INTEGER FROM private.staff_event_outbox WHERE source_id=current_setting('test.incident')::UUID),2,'one event per current team member after duplicate mutation');
SELECT ok(NOT EXISTS(SELECT 1 FROM private.staff_event_outbox o WHERE source_id=current_setting('test.incident')::UUID AND to_jsonb(o)::TEXT LIKE '%Sensitive synthetic%'),'notification metadata excludes titles and timeline contents');
SELECT private.process_staff_inbox(100);
SELECT private.process_staff_inbox(100);
SELECT is((SELECT count(*)::INTEGER FROM private.staff_inbox_deliveries d JOIN private.staff_event_outbox o USING(event_id) WHERE o.source_id=current_setting('test.incident')::UUID),2,'worker retry does not duplicate deliveries');
SET LOCAL ROLE authenticated;
SELECT is((SELECT count(*)::INTEGER FROM public.admin_staff_inbox_page('assigned','incidents')),1,'commander sees assigned notification');
SELECT is((SELECT destination FROM public.admin_staff_inbox_page('all','incidents')),'/incidents/records/'||current_setting('test.incident'),'destination binds to the exact incident');
SELECT is((SELECT count(*)::INTEGER FROM public.admin_staff_inbox_page('urgent','incidents')),1,'SEV1 changes are urgent');
SELECT pg_temp.claim(8);
SELECT is((SELECT count(*)::INTEGER FROM public.admin_staff_inbox_page('all','incidents')),0,'unassigned admin has no delivered notice');
SELECT pg_temp.claim(3);
SELECT is((SELECT count(*)::INTEGER FROM public.admin_staff_inbox_page('all','incidents')),0,'moderator has no incident notices');
SELECT pg_temp.claim(4);
SELECT is((SELECT count(*)::INTEGER FROM public.admin_staff_inbox_page('all','incidents')),0,'support has no incident notices');
SELECT pg_temp.claim(5);
SELECT is((SELECT count(*)::INTEGER FROM public.admin_staff_inbox_page('all','incidents')),0,'analyst has no incident notices');
SELECT pg_temp.claim(6);
SELECT is((SELECT count(*)::INTEGER FROM public.admin_staff_inbox_page('all','incidents')),0,'auditor has no incident notices');
SELECT pg_temp.claim(7);
SELECT throws_like($$SELECT public.admin_staff_inbox_page('all','incidents')$$,'%not_authorized%','member cannot read staff inbox');
SELECT pg_temp.claim(1);
SELECT pg_temp.command('coordinate',(pg_temp.payload()-'title')||jsonb_build_object('deadline',now()-interval '1 minute'));
RESET ROLE;
SELECT is(private.reconcile_incident_deadlines(),2,'deadline produces one notice per current responder');
SELECT is(private.reconcile_incident_deadlines(),0,'deadline retry produces no duplicates');
SET LOCAL timezone='Pacific/Auckland';
SELECT is(private.reconcile_incident_deadlines(),0,'idempotency key is independent of worker time zone');
SET LOCAL timezone='UTC';
SELECT private.process_staff_inbox(100);
SET LOCAL ROLE authenticated;
SELECT pg_temp.claim(2);
SELECT is((SELECT count(*)::INTEGER FROM public.admin_staff_inbox_page('all','incidents') WHERE kind='incident_overdue'),1,'responder receives deadline notice');
SELECT pg_temp.claim(1);
SELECT pg_temp.command('coordinate',(pg_temp.payload()-'title')||'{"responders":[]}');
RESET ROLE;
SELECT private.process_staff_inbox(100);
SET LOCAL ROLE authenticated;
SELECT pg_temp.claim(2);
SELECT is((SELECT count(*)::INTEGER FROM public.admin_staff_inbox_page('all','incidents')),0,'removed responder loses access to previously delivered notices');
SELECT pg_temp.claim(1);
SELECT is((SELECT count(*)::INTEGER FROM public.admin_staff_inbox_page('all','incidents') WHERE kind='incident_overdue'),0,'rescheduled future deadline hides obsolete overdue notice');
SELECT public.admin_configure_incident_notices(gen_random_uuid(),false);
SELECT is((SELECT count(*)::INTEGER FROM public.admin_staff_inbox_page('all','incidents')),0,'source rollback hides delivered notices');
SELECT public.admin_configure_incident_notices(gen_random_uuid(),true);
RESET ROLE;
UPDATE public.users SET account_status='suspended' WHERE user_id='1a740000-0000-4000-8000-000000000001';
SET LOCAL ROLE authenticated;
SELECT throws_like($$SELECT public.admin_staff_inbox_page('all','incidents')$$,'%not_authorized%','suspension takes effect with the same JWT');
RESET ROLE;
SELECT ok(EXISTS(SELECT 1 FROM private.staff_inbox_deliveries d JOIN private.staff_event_outbox o USING(event_id) WHERE o.source_id=current_setting('test.incident')::UUID),'rollback and revocation preserve delivery history');
SELECT * FROM finish();
ROLLBACK;
