BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SELECT no_plan();
SET session_replication_role=replica;
INSERT INTO public.users(user_id,anonymous_pseudonym,avatar_seed,recovery_key_hash,display_name,display_name_normalized,username_normalized,user_role,account_status,birth_year)
SELECT ('1a750000-0000-4000-8000-'||lpad(n::TEXT,12,'0'))::UUID,'incidentpilot'||n,'incidentpilot'||n,'x','Pilot Operator','pilot operator','incidentpilot'||n,r::public.user_role_type,'active',1990
FROM (VALUES(1,'super_admin'),(2,'admin'),(3,'moderator'),(4,'support'),(5,'analyst'),(6,'read_only_auditor'),(7,'normal'),(8,'admin'))t(n,r);
INSERT INTO auth.users(id,aud,role,created_at,updated_at) SELECT user_id,'authenticated','authenticated',now(),now() FROM public.users WHERE anonymous_pseudonym LIKE 'incidentpilot%';
SET session_replication_role=origin;
CREATE FUNCTION pg_temp.claim(n INTEGER,aal TEXT DEFAULT 'aal2') RETURNS VOID LANGUAGE sql AS $$SELECT set_config('request.jwt.claims',jsonb_build_object('sub','1a750000-0000-4000-8000-'||lpad(n::TEXT,12,'0'),'role','authenticated','aal',aal)::TEXT,true)::TEXT;$$;
CREATE FUNCTION pg_temp.payload() RETURNS JSONB LANGUAGE sql AS $$SELECT jsonb_build_object('title','Sensitive synthetic title','severity','sev1','services',ARRAY['push'],'commander','1a750000-0000-4000-8000-000000000001','responders',ARRAY['1a750000-0000-4000-8000-000000000002'],'deadline',now()+interval '1 hour','runbook','delivery','signal','push-dead','note','Sensitive synthetic note');$$;
CREATE FUNCTION pg_temp.command(command TEXT,payload JSONB) RETURNS UUID LANGUAGE sql AS $$SELECT public.admin_incident_mutate(gen_random_uuid(),current_setting('test.incident')::UUID,(public.admin_incident_detail(current_setting('test.incident')::UUID)->'incident'->>'version')::BIGINT,command,payload);$$;
SELECT ok(NOT has_function_privilege('authenticated','private.reconcile_incident_deadlines()','EXECUTE'),'clients cannot invoke deadline worker');
SELECT ok(NOT has_function_privilege('anon','public.admin_configure_incident_notices(uuid,boolean)','EXECUTE'),'anonymous configuration denied');

CREATE FUNCTION pg_temp.badge() RETURNS JSONB LANGUAGE sql AS $$SELECT q FROM jsonb_array_elements(public.admin_staff_attention()->'queues')q WHERE q->>'key'='incidents';$$;
SELECT is((SELECT audience_roles FROM private.incident_control),ARRAY['super_admin'],'default audience is super admins only');
SELECT ok(NOT has_function_privilege('authenticated','private.incident_pilot_member(uuid)','EXECUTE'),'private cohort helper not callable by clients');
SELECT ok(NOT has_function_privilege('anon','public.admin_configure_incident_audience(uuid,text[])','EXECUTE'),'anonymous audience configuration denied');
UPDATE private.staff_inbox_control SET enabled=true,audience_roles=ARRAY['super_admin','admin','moderator','support','analyst','read_only_auditor'];
SET LOCAL ROLE authenticated;
SELECT pg_temp.claim(1,'aal1');
SELECT throws_like($$SELECT public.admin_configure_incident_audience(gen_random_uuid(),ARRAY['super_admin','admin'])$$,'%aal2_required%','audience changes require MFA');
SELECT pg_temp.claim(1);
SELECT public.admin_configure_incidents(gen_random_uuid(),true);
SELECT public.admin_configure_incident_notices(gen_random_uuid(),true);
SELECT throws_like($$SELECT public.admin_configure_incident_audience(gen_random_uuid(),ARRAY['super_admin','moderator'])$$,'%invalid_audience%','role broadening rejected');
SELECT throws_like($$SELECT public.admin_configure_incident_audience(gen_random_uuid(),ARRAY['admin'])$$,'%invalid_audience%','super admin cannot be removed');
SELECT throws_like($$SELECT public.admin_configure_incident_audience(gen_random_uuid(),ARRAY['super_admin',NULL])$$,'%invalid_audience%','null roles rejected');
SELECT throws_like($$SELECT public.admin_configure_incident_audience(gen_random_uuid(),ARRAY['super_admin','super_admin'])$$,'%invalid_audience%','duplicate roles rejected');
SELECT throws_like($$SELECT public.admin_incident_mutate(gen_random_uuid(),NULL,NULL,'declare',pg_temp.payload())$$,'%invalid_staff%','cannot assign an out-of-pilot responder');
SELECT is((SELECT count(*)::INTEGER FROM public.admin_incident_staff() WHERE staff_id='1a750000-0000-4000-8000-000000000002'),0,'selector excludes out-of-pilot admin');
SELECT set_config('test.incident',public.admin_incident_mutate(gen_random_uuid(),NULL,NULL,'declare',pg_temp.payload()||'{"responders":[]}')::TEXT,true);
SELECT is(pg_temp.badge()->>'stale','true','new mutation marks badge unknown until reconciliation');
SELECT pg_temp.claim(2);
SELECT is(public.admin_incident_queue()->>'enabled','false','direct API admin read fails closed outside cohort');
SELECT is(public.admin_incident_detail(current_setting('test.incident')::UUID)->>'enabled','false','known ID cannot bypass cohort');
SELECT is((SELECT count(*)::INTEGER FROM public.admin_incident_staff()),0,'out-of-pilot selector empty');
SELECT throws_like($$SELECT public.admin_incident_mutate(gen_random_uuid(),current_setting('test.incident')::UUID,1,'note','{"kind":"update","note":"Bypass"}')$$,'%incident_disabled%','out-of-pilot mutation denied');
SELECT throws_like($$SELECT public.admin_configure_incident_audience(gen_random_uuid(),ARRAY['super_admin','admin'])$$,'%not_authorized%','ordinary admin cannot self-enroll');
SELECT is(pg_temp.badge(),NULL::JSONB,'out-of-pilot admin cannot see incident badge');
SELECT pg_temp.claim(1);
SELECT lives_ok($$SELECT public.admin_configure_incident_audience('1a750000-1000-4000-8000-000000000001',ARRAY['super_admin','admin'])$$,'explicit expansion allowed');
SELECT lives_ok($$SELECT public.admin_configure_incident_audience('1a750000-1000-4000-8000-000000000001',ARRAY['admin','super_admin'])$$,'canonical audience retry idempotent');
SELECT throws_like($$SELECT public.admin_configure_incident_audience('1a750000-1000-4000-8000-000000000001',ARRAY['super_admin'])$$,'%idempotency_payload_mismatch%','changed retry refused');
SELECT pg_temp.command('coordinate',pg_temp.payload()-'title');
SELECT pg_temp.claim(2);
SELECT is(public.admin_incident_detail(current_setting('test.incident')::UUID)->>'enabled','true','expanded cohort can read');
RESET ROLE;
SELECT private.process_staff_inbox(100);
SET LOCAL ROLE authenticated;
SELECT is(pg_temp.badge()->>'stale','false','worker reconciles badge');
SELECT is((SELECT count(*)::INTEGER FROM public.admin_staff_inbox_page('unread','incidents')),1,'expanded responder receives notice');
SELECT public.admin_staff_inbox_set_read(ARRAY[(SELECT event_id FROM public.admin_staff_inbox_page('unread','incidents') LIMIT 1)],true);
SELECT is(pg_temp.badge()->>'count','1','reading notification does not change incident workload');
SELECT pg_temp.claim(1);
SELECT public.admin_configure_incident_audience(gen_random_uuid(),ARRAY['super_admin']);
SELECT pg_temp.claim(2);
SELECT is((SELECT count(*)::INTEGER FROM public.admin_staff_inbox_page('all','incidents')),0,'cohort revocation hides existing deliveries immediately');
SELECT is(pg_temp.badge(),NULL::JSONB,'cohort revocation removes badge with same JWT');
SELECT is(public.admin_incident_queue()->>'enabled','false','cohort revocation removes API access with same JWT');
RESET ROLE;
UPDATE private.operational_incidents SET response_due_at=now()-interval '1 minute' WHERE incident_id=current_setting('test.incident')::UUID;
SELECT is(private.reconcile_incident_deadlines(),1,'deadline producer excludes revoked admin');
SELECT private.process_staff_inbox(100);
SET LOCAL ROLE authenticated;
SELECT pg_temp.claim(3);
SELECT is(pg_temp.badge(),NULL::JSONB,'moderator cannot see incident badge');
SELECT pg_temp.claim(4);
SELECT is(pg_temp.badge(),NULL::JSONB,'support cannot see incident badge');
SELECT pg_temp.claim(5);
SELECT is(pg_temp.badge(),NULL::JSONB,'analyst cannot see incident badge');
SELECT pg_temp.claim(6);
SELECT is(pg_temp.badge(),NULL::JSONB,'auditor cannot see incident badge');
RESET ROLE;
UPDATE private.operational_incidents SET status='resolved' WHERE incident_id=current_setting('test.incident')::UUID;
SET LOCAL ROLE authenticated;
SELECT pg_temp.claim(1);
SELECT is(pg_temp.badge()->>'stale','true','resolution invalidates old active count');
RESET ROLE;
SELECT private.process_staff_inbox(100);
SET LOCAL ROLE authenticated;
SELECT is(pg_temp.badge()->>'count','0','resolved incident excluded from active badge');
RESET ROLE;
UPDATE private.staff_attention_snapshots SET measured_at=now()-interval '3 minutes' WHERE queue_key='incidents';
SET LOCAL ROLE authenticated;
SELECT is(pg_temp.badge()->>'stale','true','stopped reconciler never reports healthy zero');
SELECT public.admin_configure_incidents(gen_random_uuid(),false);
SELECT is(pg_temp.badge(),NULL::JSONB,'rollback removes incident badge');
SELECT public.admin_configure_incidents(gen_random_uuid(),true);
SELECT is(pg_temp.badge()->>'stale','true','re-enable requires fresh reconciliation');
RESET ROLE;
SELECT is((SELECT count(*)::INTEGER FROM private.operational_incidents WHERE incident_id=current_setting('test.incident')::UUID),1,'cohort changes and rollback preserve history');
INSERT INTO private.operational_incidents(title,severity,services,commander,response_due_at,runbook,created_by)
SELECT 'Synthetic bounded count','sev4',ARRAY['push'],'1a750000-0000-4000-8000-000000000001',now()+interval '1 hour','delivery','1a750000-0000-4000-8000-000000000001'
FROM generate_series(1,101);
SELECT private.process_staff_inbox(100);
SET LOCAL ROLE authenticated;
SELECT is(pg_temp.badge()->>'count','100','badge source read saturates at 100 for 99+ display');
SELECT is(pg_temp.badge()->>'stale','false','bounded snapshot remains current after reconciliation');
RESET ROLE;
SELECT * FROM finish();
ROLLBACK;
