-- PREPARED, NOT RUN. Requires the revised staff_invitation_ledger draft.
BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SELECT no_plan();
SET session_replication_role=replica;
INSERT INTO public.users(user_id,anonymous_pseudonym,avatar_seed,recovery_key_hash,display_name,display_name_normalized,username_normalized,user_role,account_status,birth_year)
SELECT ('1a791000-0000-4000-8000-'||lpad(n::TEXT,12,'0'))::UUID,'recoverpilot'||n,'recoverpilot'||n,'x','Recovery Operator','recovery operator','recoverpilot'||n,r::public.user_role_type,'active',1990
FROM (VALUES(1,'super_admin'),(2,'normal'),(3,'normal'),(4,'normal'),(5,'moderator'),(6,'admin'),(7,'support'),(8,'analyst'),(9,'read_only_auditor'))t(n,r);
INSERT INTO auth.users(id,aud,role,created_at,updated_at,invited_at,raw_app_meta_data) SELECT user_id,'authenticated','authenticated',now(),now(),now(),'{"staff_invite_pending":true}'::JSONB FROM public.users WHERE anonymous_pseudonym LIKE 'recoverpilot%';
SET session_replication_role=origin;
CREATE FUNCTION pg_temp.claim(n INT,aal TEXT DEFAULT 'aal2') RETURNS VOID LANGUAGE sql AS $$
SELECT set_config('request.jwt.claims',jsonb_build_object('sub','1a791000-0000-4000-8000-'||lpad(n::TEXT,12,'0'),'role','authenticated','aal',aal)::TEXT,true)::TEXT;$$;
CREATE FUNCTION pg_temp.command(cmd TEXT,v BIGINT,op UUID DEFAULT gen_random_uuid()) RETURNS VOID LANGUAGE sql AS $$
SELECT public.admin_recover_staff_invitation(op,current_setting('test.invitation')::UUID,v,cmd);$$;
SELECT ok(NOT has_function_privilege('anon','public.admin_recover_staff_invitation(uuid,uuid,bigint,text,text)','EXECUTE'),'anon cannot recover');
SET LOCAL ROLE authenticated;
SELECT pg_temp.claim(1);
SELECT public.admin_configure_invitation_ledger(gen_random_uuid(),true);
SELECT set_config('test.invitation',public.admin_begin_staff_invitation(gen_random_uuid(),repeat('b',64),'recoverpilot2','moderator')->>'invitation_id',true);
SELECT pg_temp.claim(1,'aal1');
SELECT throws_like($$SELECT pg_temp.command('reconcile',1)$$,'%aal2_required%','MFA required');
SELECT pg_temp.claim(1);
SELECT lives_ok($$SELECT pg_temp.command('reconcile',1,'1a791000-1000-4000-8000-000000000001')$$,'recover a lost provider response from actual invitation evidence');
SELECT lives_ok($$SELECT pg_temp.command('reconcile',1,'1a791000-1000-4000-8000-000000000001')$$,'same operation retry idempotent');
SELECT throws_like($$SELECT pg_temp.command('cancel',1,'1a791000-1000-4000-8000-000000000001')$$,'%idempotency_payload_mismatch%','same operation different intent refused');
SELECT throws_like($$SELECT pg_temp.command('cancel',1)$$,'%invitation_conflict%','stale version refused');
RESET ROLE;
SELECT is((SELECT user_role::TEXT FROM public.users WHERE anonymous_pseudonym='recoverpilot2'),'normal','reconciliation does not grant a role');
SET LOCAL ROLE authenticated;
SELECT pg_temp.claim(1);
SELECT lives_ok($$SELECT pg_temp.command('cancel',2)$$,'cancel pending grant');
SELECT throws_like($$SELECT pg_temp.command('complete_grant',3)$$,'%invitation_grant_closed%','cancelled attempt cannot grant');
SELECT throws_like($$SELECT public.admin_record_staff_invitation(current_setting('test.invitation')::UUID,'1a791000-0000-4000-8000-000000000002','provider_accepted')$$,'%invitation_grant_closed%','late original provider callback cannot reopen cancellation');
SELECT set_config('test.invitation',public.admin_begin_staff_invitation(gen_random_uuid(),repeat('c',64),'recoverpilot3','support')->>'invitation_id',true);
SELECT pg_temp.command('reconcile',1);
RESET ROLE;
UPDATE private.staff_invitation_attempts SET grant_expires_at=clock_timestamp()-interval '1 second' WHERE invitation_id=current_setting('test.invitation')::UUID;
SET LOCAL ROLE authenticated;
SELECT pg_temp.claim(1);
SELECT throws_like($$SELECT pg_temp.command('complete_grant',2)$$,'%invitation_grant_closed%','expiry enforced during grant, without scheduler');
SELECT set_config('test.invitation',public.admin_begin_staff_invitation(gen_random_uuid(),repeat('d',64),'recoverpilot4','analyst')->>'invitation_id',true);
SELECT pg_temp.command('reconcile',1);
RESET ROLE;
UPDATE auth.users SET raw_app_meta_data='{}' WHERE id='1a791000-0000-4000-8000-000000000004';
SET LOCAL ROLE authenticated;
SELECT pg_temp.claim(1);
SELECT throws_like($$SELECT pg_temp.command('complete_grant',2)$$,'%invitation_setup_not_ready%','missing Auth setup marker blocks grant');
RESET ROLE;
UPDATE auth.users SET raw_app_meta_data='{"staff_invite_pending":true}' WHERE id='1a791000-0000-4000-8000-000000000004';
SET LOCAL ROLE authenticated;
SELECT pg_temp.claim(1);
SELECT lives_ok($$SELECT pg_temp.command('complete_grant',2,'1a791000-1000-4000-8000-000000000002')$$,'verified pending account receives only its requested role');
SELECT lives_ok($$SELECT pg_temp.command('complete_grant',2,'1a791000-1000-4000-8000-000000000002')$$,'completion receipt replays before stale-version check');
SELECT throws_like($$SELECT pg_temp.command('cancel',3)$$,'%invitation_access_exists%','cancellation cannot silently demote assigned staff');
SELECT throws_like($$SELECT pg_temp.command('resend',3)$$,'%invalid_input%','unsupported resend never dispatched');
RESET ROLE;
SELECT is((SELECT user_role::TEXT FROM public.users WHERE anonymous_pseudonym='recoverpilot4'),'analyst','server derives requested role');
SELECT is((SELECT count(*)::INT FROM private.staff_invitation_events WHERE invitation_id=current_setting('test.invitation')::UUID AND stage='access_assigned'),1,'completion records once');
SET LOCAL ROLE authenticated;
SELECT pg_temp.claim(5);
SELECT throws_like($$SELECT pg_temp.command('reconcile',3)$$,'%not_authorized%','moderator denied');
SELECT pg_temp.claim(6);
SELECT throws_like($$SELECT pg_temp.command('reconcile',3)$$,'%not_authorized%','admin denied');
SELECT pg_temp.claim(7);
SELECT throws_like($$SELECT pg_temp.command('reconcile',3)$$,'%not_authorized%','support denied');
SELECT pg_temp.claim(8);
SELECT throws_like($$SELECT pg_temp.command('reconcile',3)$$,'%not_authorized%','analyst denied');
SELECT pg_temp.claim(9);
SELECT throws_like($$SELECT pg_temp.command('reconcile',3)$$,'%not_authorized%','auditor denied');
SELECT pg_temp.claim(1);
SELECT public.admin_configure_invitation_ledger(gen_random_uuid(),false);
SELECT throws_like($$SELECT pg_temp.command('reconcile',3)$$,'%invitation_ledger_disabled%','disabled backend blocks recovery');
SELECT * FROM finish();
ROLLBACK;
