const int maxGroupInviteTokenLength = 128;

// Group invite tokens are UUIDs generated by Postgres. Keeping this check in
// the app as well prevents malformed deep links from reaching the RPC boundary
// and producing noisy UUID-cast failures.
final RegExp _groupInviteTokenPattern = RegExp(
  r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$',
  caseSensitive: false,
);

String? normalizeGroupInviteToken(String? value) {
  final normalized = value?.trim();
  if (normalized == null ||
      normalized.isEmpty ||
      normalized.length > maxGroupInviteTokenLength ||
      !_groupInviteTokenPattern.hasMatch(normalized)) {
    return null;
  }
  return normalized.toLowerCase();
}

/// Builds the only invite URI shape registered by the app.
///
/// Throws instead of silently sharing an unusable or attacker-controlled URI.
Uri groupInviteUri(String token) {
  final normalized = normalizeGroupInviteToken(token);
  if (normalized == null) {
    throw const FormatException('Invalid group invite token');
  }
  return Uri(
    scheme: 'venttly',
    host: 'group-invite',
    pathSegments: [normalized],
  );
}

/// Converts a public invite URI into its internal route.
///
/// Query parameters, fragments, credentials, ports, extra path segments, and
/// non-UUID tokens are rejected so a capability link cannot smuggle unrelated
/// state into navigation or trigger malformed backend requests.
String? groupInviteRouteFromUri(Uri uri) {
  if (uri.scheme.toLowerCase() != 'venttly' ||
      uri.hasQuery ||
      uri.hasFragment ||
      uri.userInfo.isNotEmpty ||
      uri.hasPort) {
    return null;
  }

  String? token;
  if (uri.host.toLowerCase() == 'group-invite' &&
      uri.pathSegments.length == 1) {
    token = uri.pathSegments.single;
  } else if (uri.host.isEmpty &&
      uri.pathSegments.length == 2 &&
      uri.pathSegments.first.toLowerCase() == 'group-invite') {
    token = uri.pathSegments.last;
  }

  final normalized = normalizeGroupInviteToken(token);
  if (normalized == null) return null;
  return '/group-invite/${Uri.encodeComponent(normalized)}';
}
