export function isOwnedStoragePath(path: string, userId: string): boolean {
  if (!path || path.includes("\\") || path.includes("..")) return false;
  const parts = path.split("/");
  return parts.length === 2 && parts[0] === userId && parts[1].length > 0;
}

/** Resolve only URLs generated by this Supabase project's public bucket. */
export function ownedPathFromPublicUrl(
  rawUrl: string,
  supabaseUrl: string,
  bucket: string,
  userId: string,
): string | null {
  try {
    const candidate = new URL(rawUrl);
    const project = new URL(supabaseUrl);
    if (candidate.origin !== project.origin) return null;
    const prefix = `/storage/v1/object/public/${bucket}/`;
    if (!candidate.pathname.startsWith(prefix)) return null;
    const path = decodeURIComponent(candidate.pathname.slice(prefix.length));
    return isOwnedStoragePath(path, userId) ? path : null;
  } catch {
    return null;
  }
}
