-- Generated by `supabase migration new staff_inbox_foundation`, then ordered
-- immediately after the repository's future-dated operational governance
-- migration (20261029090000). Additive, disabled by default; no old assignment
-- fanout. Overdue support cases are reconciled in bounded batches when enabled.
-- First source adapters: support assignment/SLA and legal approval requests.
-- Incident/job/export adapters are deliberately not claimed by this migration.

CREATE TABLE private.staff_inbox_control (
  singleton BOOLEAN PRIMARY KEY DEFAULT true CHECK (singleton),
  enabled BOOLEAN NOT NULL DEFAULT false,
  audience_roles TEXT[] NOT NULL DEFAULT ARRAY['super_admin'] CHECK (
    cardinality(audience_roles) BETWEEN 1 AND 6 AND
    audience_roles <@ ARRAY['super_admin','admin','moderator','support','analyst','read_only_auditor']::TEXT[] AND
    array_position(audience_roles,NULL) IS NULL),
  worker_at TIMESTAMPTZ
);
INSERT INTO private.staff_inbox_control DEFAULT VALUES;

CREATE TABLE private.staff_event_outbox (
  event_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  event_key TEXT NOT NULL UNIQUE CHECK (length(event_key) <= 200),
  kind TEXT NOT NULL CHECK (kind IN ('support_assigned','support_sla_breached','legal_review_requested')),
  source_id UUID NOT NULL,
  intended_recipient UUID,
  severity TEXT NOT NULL CHECK (severity IN ('info','warning','critical')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','delivered','failed','skipped')),
  attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts BETWEEN 0 AND 5),
  next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  delivered_at TIMESTAMPTZ,
  last_error_code TEXT CHECK (last_error_code ~ '^[A-Z0-9]{5}$')
);
CREATE INDEX staff_event_outbox_pending_idx ON private.staff_event_outbox(next_attempt_at,event_id) WHERE status='pending';
CREATE TABLE private.staff_inbox_deliveries (
  event_id UUID NOT NULL REFERENCES private.staff_event_outbox(event_id),
  recipient_id UUID NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
  delivered_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  read_at TIMESTAMPTZ,
  PRIMARY KEY (recipient_id,event_id)
);
CREATE INDEX staff_inbox_delivery_cursor_idx ON private.staff_inbox_deliveries(recipient_id,delivered_at DESC,event_id DESC);
CREATE INDEX staff_inbox_unread_idx ON private.staff_inbox_deliveries(recipient_id,event_id) WHERE read_at IS NULL;
CREATE INDEX staff_inbox_event_idx ON private.staff_inbox_deliveries(event_id);
CREATE TABLE private.staff_inbox_preferences (
  staff_id UUID PRIMARY KEY REFERENCES public.users(user_id) ON DELETE CASCADE,
  assignment_notifications BOOLEAN NOT NULL DEFAULT true
);
CREATE TABLE private.staff_attention_snapshots (
  queue_key TEXT PRIMARY KEY CHECK (queue_key IN ('support','legal')),
  open_count BIGINT NOT NULL CHECK (open_count >= 0),
  measured_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE private.staff_inbox_control ENABLE ROW LEVEL SECURITY;
ALTER TABLE private.staff_event_outbox ENABLE ROW LEVEL SECURITY;
ALTER TABLE private.staff_inbox_deliveries ENABLE ROW LEVEL SECURITY;
ALTER TABLE private.staff_inbox_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE private.staff_attention_snapshots ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON private.staff_inbox_control, private.staff_event_outbox,
  private.staff_inbox_deliveries, private.staff_inbox_preferences,
  private.staff_attention_snapshots FROM PUBLIC, anon, authenticated;

-- Unexposed helper, called only within actor-bound definer RPCs/worker. Current
-- source visibility is checked again on every read, including after demotion.
CREATE FUNCTION private.can_read_staff_event(p_actor UUID,p_kind TEXT,p_source UUID)
RETURNS BOOLEAN LANGUAGE sql STABLE SET search_path='' AS $$
  SELECT CASE
    WHEN p_kind IN ('support_assigned','support_sla_breached') THEN
      public.is_staff(p_actor,ARRAY['super_admin','admin','support'])
      AND EXISTS(SELECT 1 FROM private.support_cases c WHERE c.support_case_id=p_source)
    WHEN p_kind='legal_review_requested' THEN
      public.is_staff(p_actor,ARRAY['super_admin'])
      AND EXISTS(SELECT 1 FROM private.legal_requests l WHERE l.legal_request_id=p_source AND l.created_by<>p_actor)
    ELSE false END;
$$;
REVOKE ALL ON FUNCTION private.can_read_staff_event(UUID,TEXT,UUID) FROM PUBLIC,anon,authenticated;

CREATE FUNCTION private.enqueue_staff_source_event()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
BEGIN
  IF NOT (SELECT enabled FROM private.staff_inbox_control WHERE singleton) THEN RETURN NEW; END IF;
  IF TG_TABLE_NAME='support_cases' THEN
    IF NEW.assigned_to IS NOT NULL AND (TG_OP='INSERT' OR NEW.assigned_to IS DISTINCT FROM OLD.assigned_to) THEN
      INSERT INTO private.staff_event_outbox(event_key,kind,source_id,intended_recipient,severity)
      VALUES('support-assigned:'||NEW.support_case_id||':'||gen_random_uuid(), 'support_assigned',
        NEW.support_case_id,NEW.assigned_to,CASE WHEN NEW.priority='critical' THEN 'critical' ELSE 'info' END);
    END IF;
  ELSIF TG_TABLE_NAME='legal_requests' THEN
    IF NEW.status='awaiting_approval' AND (TG_OP='INSERT' OR NEW.status IS DISTINCT FROM OLD.status) THEN
      INSERT INTO private.staff_event_outbox(event_key,kind,source_id,severity)
      VALUES('legal-review:'||NEW.legal_request_id||':'||gen_random_uuid(),'legal_review_requested',NEW.legal_request_id,'warning');
    END IF;
  END IF;
  RETURN NEW;
END;
$$;
REVOKE ALL ON FUNCTION private.enqueue_staff_source_event() FROM PUBLIC,anon,authenticated;
CREATE TRIGGER support_staff_inbox_event AFTER INSERT OR UPDATE OF assigned_to ON private.support_cases
  FOR EACH ROW EXECUTE FUNCTION private.enqueue_staff_source_event();
CREATE TRIGGER legal_staff_inbox_event AFTER INSERT OR UPDATE OF status ON private.legal_requests
  FOR EACH ROW EXECUTE FUNCTION private.enqueue_staff_source_event();

-- Fixed worker entry point, not exposed to clients. At most 100 outbox events
-- per invocation, atomic deliveries + receipt, SKIP LOCKED and bounded retries.
CREATE FUNCTION private.process_staff_inbox(p_limit INTEGER DEFAULT 100)
RETURNS INTEGER LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE e private.staff_event_outbox%ROWTYPE; processed INTEGER:=0;
BEGIN
  IF p_limit IS NULL OR p_limit NOT BETWEEN 1 AND 100 THEN RAISE EXCEPTION 'invalid_limit'; END IF;
  IF NOT (SELECT enabled FROM private.staff_inbox_control WHERE singleton) THEN RETURN 0; END IF;
  IF NOT pg_try_advisory_xact_lock(hashtextextended('staff-inbox-worker',0)) THEN RETURN 0; END IF;

  -- Bounded SLA reconciliation, indexed by the canonical operational queue.
  INSERT INTO private.staff_event_outbox(event_key,kind,source_id,intended_recipient,severity)
  SELECT 'support-sla:'||c.support_case_id||':'||c.sla_due_at::TEXT,'support_sla_breached',
    c.support_case_id,c.assigned_to,'critical'
  FROM private.support_cases c
  WHERE c.status NOT IN ('resolved','closed') AND c.sla_due_at<now()
    AND NOT EXISTS(SELECT 1 FROM private.staff_event_outbox o WHERE o.event_key='support-sla:'||c.support_case_id||':'||c.sla_due_at::TEXT)
  ORDER BY c.sla_due_at,c.support_case_id LIMIT p_limit
  ON CONFLICT(event_key) DO NOTHING;

  FOR e IN SELECT * FROM private.staff_event_outbox
    WHERE status='pending' AND next_attempt_at<=now()
    ORDER BY next_attempt_at,event_id FOR UPDATE SKIP LOCKED LIMIT p_limit
  LOOP
    BEGIN
      INSERT INTO private.staff_inbox_deliveries(event_id,recipient_id)
      SELECT e.event_id,u.user_id FROM public.users u
      WHERE u.user_role::TEXT IN ('super_admin','admin','support')
        AND u.user_role::TEXT=ANY((SELECT audience_roles FROM private.staff_inbox_control WHERE singleton)::TEXT[])
        AND (e.intended_recipient IS NULL OR u.user_id=e.intended_recipient)
        AND private.can_read_staff_event(u.user_id,e.kind,e.source_id)
        AND (e.kind<>'support_assigned' OR e.severity='critical' OR COALESCE(
          (SELECT p.assignment_notifications FROM private.staff_inbox_preferences p WHERE p.staff_id=u.user_id),true))
      ON CONFLICT(recipient_id,event_id) DO NOTHING;
      UPDATE private.staff_event_outbox SET status=CASE WHEN EXISTS(
        SELECT 1 FROM private.staff_inbox_deliveries d WHERE d.event_id=e.event_id
      ) THEN 'delivered' ELSE 'skipped' END,delivered_at=now(),attempts=attempts+1,last_error_code=NULL WHERE event_id=e.event_id;
      processed:=processed+1;
    EXCEPTION WHEN OTHERS THEN
      UPDATE private.staff_event_outbox SET attempts=attempts+1,
        status=CASE WHEN attempts+1>=5 THEN 'failed' ELSE 'pending' END,
        next_attempt_at=now()+make_interval(secs=>LEAST(3600,30*(2^attempts)::INTEGER)),
        last_error_code=SQLSTATE WHERE event_id=e.event_id;
    END;
  END LOOP;
  INSERT INTO private.staff_attention_snapshots(queue_key,open_count,measured_at)
  VALUES ('support',(SELECT count(*) FROM private.support_cases WHERE status NOT IN ('resolved','closed')),now()),
    ('legal',(SELECT count(*) FROM private.legal_requests WHERE status='awaiting_approval'),now())
  ON CONFLICT(queue_key) DO UPDATE SET open_count=EXCLUDED.open_count,measured_at=EXCLUDED.measured_at;
  UPDATE private.staff_inbox_control SET worker_at=now() WHERE singleton;
  RETURN processed;
END;
$$;
REVOKE ALL ON FUNCTION private.process_staff_inbox(INTEGER) FROM PUBLIC,anon,authenticated;

CREATE FUNCTION public.admin_staff_inbox(
  p_filter TEXT DEFAULT 'all',p_limit INTEGER DEFAULT 30,
  p_before_at TIMESTAMPTZ DEFAULT NULL,p_before_id UUID DEFAULT NULL
) RETURNS TABLE(event_id UUID,kind TEXT,severity TEXT,source_id UUID,destination TEXT,delivered_at TIMESTAMPTZ,read_at TIMESTAMPTZ)
LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE actor UUID:=auth.uid();
BEGIN
  IF NOT public.is_staff(actor,ARRAY['super_admin','admin','moderator','support','analyst','read_only_auditor']) THEN RAISE EXCEPTION 'not_authorized' USING ERRCODE='42501'; END IF;
  IF NOT public.claim_rate_limit('staff_inbox_read',60,120) THEN RAISE EXCEPTION 'rate_limited'; END IF;
  IF p_filter IS NULL OR p_filter NOT IN ('all','unread','urgent','assigned') OR p_limit IS NULL OR p_limit NOT BETWEEN 1 AND 100
    OR ((p_before_at IS NULL)<>(p_before_id IS NULL)) THEN RAISE EXCEPTION 'invalid_inbox_query' USING ERRCODE='22023'; END IF;
  IF NOT (SELECT enabled AND public.is_staff(actor,audience_roles) FROM private.staff_inbox_control WHERE singleton) THEN RETURN; END IF;
  RETURN QUERY
    SELECT o.event_id,o.kind,o.severity,o.source_id,
      CASE WHEN o.kind='legal_review_requested' THEN '/legal-requests' ELSE '/support/cases' END,
      d.delivered_at,d.read_at
    FROM private.staff_inbox_deliveries d JOIN private.staff_event_outbox o USING(event_id)
    WHERE d.recipient_id=actor AND private.can_read_staff_event(actor,o.kind,o.source_id)
      AND (p_filter<>'unread' OR d.read_at IS NULL)
      AND (p_filter<>'urgent' OR o.severity='critical')
      AND (p_filter<>'assigned' OR EXISTS(SELECT 1 FROM private.support_cases c
        WHERE c.support_case_id=o.source_id AND c.assigned_to=actor AND c.status NOT IN ('resolved','closed')))
      AND (p_before_at IS NULL OR (d.delivered_at,d.event_id)<(p_before_at,p_before_id))
    ORDER BY d.delivered_at DESC,d.event_id DESC LIMIT p_limit;
END;
$$;

CREATE FUNCTION public.admin_staff_inbox_set_read(p_events UUID[],p_read BOOLEAN)
RETURNS INTEGER LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE actor UUID:=auth.uid(); changed INTEGER;
BEGIN
  IF NOT public.is_staff(actor,ARRAY['super_admin','admin','moderator','support','analyst','read_only_auditor']) THEN RAISE EXCEPTION 'not_authorized' USING ERRCODE='42501'; END IF;
  IF NOT public.claim_rate_limit('staff_inbox_state',60,60) THEN RAISE EXCEPTION 'rate_limited'; END IF;
  IF p_read IS NULL OR p_events IS NULL OR cardinality(p_events) NOT BETWEEN 1 AND 100
    OR array_position(p_events,NULL) IS NOT NULL THEN RAISE EXCEPTION 'invalid_inbox_state' USING ERRCODE='22023'; END IF;
  IF NOT (SELECT enabled AND public.is_staff(actor,audience_roles) FROM private.staff_inbox_control WHERE singleton) THEN RAISE EXCEPTION 'inbox_disabled'; END IF;
  UPDATE private.staff_inbox_deliveries d SET read_at=CASE WHEN p_read THEN COALESCE(d.read_at,now()) ELSE NULL END
  FROM private.staff_event_outbox o WHERE o.event_id=d.event_id AND d.recipient_id=actor
    AND d.event_id=ANY(p_events) AND private.can_read_staff_event(actor,o.kind,o.source_id)
    AND ((p_read AND d.read_at IS NULL) OR (NOT p_read AND d.read_at IS NOT NULL));
  GET DIAGNOSTICS changed=ROW_COUNT;
  RETURN changed;
END;
$$;

CREATE FUNCTION public.admin_staff_inbox_preferences(p_assignment_notifications BOOLEAN DEFAULT NULL)
RETURNS BOOLEAN LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE actor UUID:=auth.uid();
BEGIN
  IF NOT public.is_staff(actor,ARRAY['super_admin','admin','moderator','support','analyst','read_only_auditor']) THEN RAISE EXCEPTION 'not_authorized' USING ERRCODE='42501'; END IF;
  IF NOT public.claim_rate_limit('staff_inbox_preferences',60,30) THEN RAISE EXCEPTION 'rate_limited'; END IF;
  IF p_assignment_notifications IS NOT NULL THEN
    INSERT INTO private.staff_inbox_preferences(staff_id,assignment_notifications) VALUES(actor,p_assignment_notifications)
    ON CONFLICT(staff_id) DO UPDATE SET assignment_notifications=EXCLUDED.assignment_notifications;
  END IF;
  RETURN COALESCE((SELECT assignment_notifications FROM private.staff_inbox_preferences WHERE staff_id=actor),true);
END;
$$;

CREATE FUNCTION public.admin_staff_attention()
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE actor UUID:=auth.uid(); control private.staff_inbox_control%ROWTYPE; unread INTEGER; queues JSONB;
BEGIN
  IF NOT public.is_staff(actor,ARRAY['super_admin','admin','moderator','support','analyst','read_only_auditor']) THEN RAISE EXCEPTION 'not_authorized' USING ERRCODE='42501'; END IF;
  IF NOT public.claim_rate_limit('staff_attention_read',60,120) THEN RAISE EXCEPTION 'rate_limited'; END IF;
  SELECT * INTO control FROM private.staff_inbox_control WHERE singleton;
  IF NOT control.enabled OR NOT public.is_staff(actor,control.audience_roles) THEN RETURN jsonb_build_object('enabled',false); END IF;
  SELECT count(*) INTO unread FROM (SELECT 1 FROM private.staff_inbox_deliveries d
    JOIN private.staff_event_outbox o USING(event_id)
    WHERE d.recipient_id=actor AND d.read_at IS NULL
      AND private.can_read_staff_event(actor,o.kind,o.source_id) LIMIT 100) capped;
  SELECT COALESCE(jsonb_agg(jsonb_build_object('key',s.queue_key,'count',s.open_count,
    'measured_at',s.measured_at,'stale',s.measured_at<now()-interval '2 minutes')),'[]'::JSONB)
  INTO queues FROM private.staff_attention_snapshots s WHERE
    (s.queue_key='support' AND public.is_staff(actor,ARRAY['super_admin','admin','support'])) OR
    (s.queue_key='legal' AND public.is_staff(actor,ARRAY['super_admin']));
  RETURN jsonb_build_object('enabled',true,'unread_count',LEAST(unread,99),'unread_more',unread>99,
    'generated_at',now(),'worker_at',control.worker_at,'queues',queues);
END;
$$;

REVOKE ALL ON FUNCTION public.admin_staff_inbox(TEXT,INTEGER,TIMESTAMPTZ,UUID) FROM PUBLIC,anon;
REVOKE ALL ON FUNCTION public.admin_staff_inbox_set_read(UUID[],BOOLEAN) FROM PUBLIC,anon;
REVOKE ALL ON FUNCTION public.admin_staff_inbox_preferences(BOOLEAN) FROM PUBLIC,anon;
REVOKE ALL ON FUNCTION public.admin_staff_attention() FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.admin_staff_inbox(TEXT,INTEGER,TIMESTAMPTZ,UUID),
  public.admin_staff_inbox_set_read(UUID[],BOOLEAN),public.admin_staff_inbox_preferences(BOOLEAN),
  public.admin_staff_attention() TO authenticated;

CREATE FUNCTION public.admin_configure_staff_inbox(p_operation UUID,p_enabled BOOLEAN,p_roles TEXT[] DEFAULT ARRAY['super_admin'])
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE actor UUID:=auth.uid(); request JSONB:=jsonb_build_object('enabled',p_enabled,'roles',p_roles);
BEGIN
  IF NOT public.is_staff(actor,ARRAY['super_admin']) THEN RAISE EXCEPTION 'not_authorized' USING ERRCODE='42501'; END IF;
  PERFORM private.require_aal2();
  IF p_enabled IS NULL OR p_roles IS NULL OR cardinality(p_roles) NOT BETWEEN 1 AND 6
    OR NOT (p_roles <@ ARRAY['super_admin','admin','moderator','support','analyst','read_only_auditor']::TEXT[])
    OR array_position(p_roles,NULL) IS NOT NULL THEN RAISE EXCEPTION 'invalid_rollout' USING ERRCODE='22023'; END IF;
  IF private.admin_operation_existing(actor,p_operation,'staff_inbox.configure',request) IS NOT NULL THEN RETURN; END IF;
  IF NOT public.claim_rate_limit('staff_inbox_configure',60,10) THEN RAISE EXCEPTION 'rate_limited'; END IF;
  UPDATE private.staff_inbox_control SET enabled=p_enabled,audience_roles=p_roles WHERE singleton;
  PERFORM private.record_operational_audit(actor,'staff_inbox.configure','staff_inbox',p_operation,
    'Staff inbox rollout','release_control',request);
  PERFORM private.record_admin_operation(actor,p_operation,'staff_inbox.configure',request,p_operation);
END;
$$;

CREATE FUNCTION public.admin_staff_inbox_health()
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
BEGIN
  IF NOT public.is_staff(auth.uid(),ARRAY['super_admin']) THEN RAISE EXCEPTION 'not_authorized' USING ERRCODE='42501'; END IF;
  IF NOT public.claim_rate_limit('staff_inbox_health',60,60) THEN RAISE EXCEPTION 'rate_limited'; END IF;
  RETURN (SELECT jsonb_build_object('enabled',c.enabled,'audience_roles',c.audience_roles,'worker_at',c.worker_at,
    'worker_stale',c.worker_at IS NULL OR c.worker_at<now()-interval '2 minutes',
    'pending',(SELECT count(*) FROM private.staff_event_outbox WHERE status='pending'),
    'failed',(SELECT count(*) FROM private.staff_event_outbox WHERE status='failed'),
    'oldest_pending_at',(SELECT min(created_at) FROM private.staff_event_outbox WHERE status='pending'))
    FROM private.staff_inbox_control c WHERE singleton);
END;
$$;
REVOKE ALL ON FUNCTION public.admin_configure_staff_inbox(UUID,BOOLEAN,TEXT[]),public.admin_staff_inbox_health() FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.admin_configure_staff_inbox(UUID,BOOLEAN,TEXT[]),public.admin_staff_inbox_health() TO authenticated;

-- Scheduling is harmless while disabled; activation remains an explicit release
-- operation after source/recipient validation. No browser can flip this switch.
SELECT cron.schedule('staff-inbox-dispatch','* * * * *','SELECT private.process_staff_inbox(100)');
