-- Give the founding super admin a handle a human can read.
--
-- The staff invitation flow used to generate `staff_${randomBytes(8).hex}`,
-- so the account that now holds super_admin is called
-- `staff_17cfcefe9f62b1f9`. That string is what public.audit_log records as
-- target_label on every action this account takes or receives, and it is what
-- any future staff-facing surface shows. It is not a secret, it is not
-- meaningful, and nobody can read it back to anyone.
--
-- The invite form now asks for the handle instead of generating one, so this
-- is a one-off correction for the single account created before that change.
--
-- WHY THIS NEEDS A MIGRATION AT ALL
--
-- private.guard_user_identity raises username_changes_disabled on any UPDATE
-- that changes anonymous_pseudonym. That rule is load-bearing and is not being
-- relaxed: on an app whose premise is that you can say something without it
-- being attached to you, a handle that can change is a handle that can be
-- used to impersonate someone who has left, or to shed a reputation and keep
-- the account. Members must not be able to rename themselves, and neither
-- should staff acting through the console -- which is why the Edit profile
-- field that appeared to allow it has been made read-only rather than wired up.
--
-- So the exception is made here, once, in a file that says who it applies to
-- and why, rather than by loosening the rule for everybody.
--
-- The trigger is disabled for the length of one statement rather than using
-- session_replication_role, which would also suspend foreign keys and every
-- other trigger on the table. Because the guard is also what derives
-- username_normalized, display_name and display_name_normalized, this sets all
-- four columns explicitly -- leaving username_normalized stale would break
-- users_username_normalized_unique and every lookup that goes through it.
--
-- Scoped by user_id, not by handle: there is exactly one intended target and
-- naming it by primary key means this cannot match anything else if it is
-- replayed against a database in a different state.

BEGIN;

DO $$
DECLARE
  v_target CONSTANT UUID := '5ed717d3-322b-41ab-b5f3-4de9b67493ca';
  v_old    CONSTANT TEXT := 'staff_17cfcefe9f62b1f9';
  v_new    CONSTANT TEXT := 'venttly_admin';
  v_found  TEXT;
BEGIN
  SELECT anonymous_pseudonym INTO v_found
    FROM public.users WHERE user_id = v_target;

  -- Already applied, or a database this account does not exist in. Either way
  -- there is nothing to correct and nothing to complain about.
  IF v_found IS NULL OR v_found = v_new THEN
    RAISE NOTICE 'rename skipped: % is %', v_target, COALESCE(v_found, 'absent');
    RETURN;
  END IF;

  -- Anything other than the handle this migration was written for means the
  -- account was renamed by some other route, and guessing is worse than
  -- stopping.
  IF v_found <> v_old THEN
    RAISE EXCEPTION 'expected % to be %, found %', v_target, v_old, v_found;
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.users
     WHERE lower(anonymous_pseudonym) = lower(v_new) AND user_id <> v_target
  ) THEN
    RAISE EXCEPTION 'handle % is already taken', v_new;
  END IF;

  ALTER TABLE public.users DISABLE TRIGGER users_identity_guard;

  UPDATE public.users
     SET anonymous_pseudonym     = v_new,
         username_normalized     = lower(v_new),
         display_name            = v_new,
         display_name_normalized = lower(v_new),
         updated_at              = now()
   WHERE user_id = v_target;

  ALTER TABLE public.users ENABLE TRIGGER users_identity_guard;

  -- The audit log is append-only and target_label is a snapshot taken at write
  -- time, so entries written before tonight keep saying staff_17cfcefe9f62b1f9.
  -- That is correct: they record what the account was called when the action
  -- happened. This row is what ties the two names together.
  INSERT INTO public.audit_log (
    actor_id, actor_pseudonym, actor_role, action,
    target_type, target_id, target_label,
    before_state, after_state, reason
  )
  VALUES (
    v_target, v_new, 'super_admin', 'user.rename_handle',
    'user', v_target, '@' || v_new,
    jsonb_build_object('anonymous_pseudonym', v_old),
    jsonb_build_object('anonymous_pseudonym', v_new),
    'One-off correction: handle was auto-generated by the staff invitation '
    'flow before that form asked for one. Applied by migration '
    '20261030090000.'
  );
END $$;

SELECT public.record_migration(
  '20261030090000', 'rename_founding_super_admin_handle'
);

NOTIFY pgrst, 'reload schema';

COMMIT;
